MySQL:
  user: 'root'
  database: 'minecraft'
  password: ''
  host: 'localhost'

Message: '&aYou received &d{money}&a mobcoins for killing a &d{type}&a.'

Entities:
  COW:
    Type: 'COW'
    Value: 30

  PIG:
    Type: 'PIG'
    Value: 15
